-- 코드를 입력하세요
SELECT O.YEAR, O.MONTH, U.GENDER, COUNT(*) AS USERS
FROM (
    SELECT O.USER_ID, YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH
    FROM ONLINE_SALE O
    GROUP BY O.USER_ID, YEAR, MONTH
) O
INNER JOIN USER_INFO U ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, U.GENDER
ORDER BY YEAR ASC, MONTH ASC, U.GENDER ASC;