-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O
INNER JOIN ANIMAL_INS I ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SUBSTR(I.SEX_UPON_INTAKE, 1, 6) = 'Intact' AND SUBSTR(O.SEX_UPON_OUTCOME, 1, 6) != 'Intact'
ORDER BY O.ANIMAL_ID ASC;