WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR, 0 AS COUNT
    UNION ALL
    SELECT HOUR+1, 0 FROM CTE
    WHERE HOUR < 23
), ABC AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
)

SELECT C.HOUR, SUM(C.COUNT + (
    CASE 
    WHEN A.COUNT IS NULL
    THEN 0
    ELSE A.COUNT
    END
)) AS COUNT
FROM CTE C
    LEFT OUTER JOIN ABC A ON A.HOUR = C.HOUR
GROUP BY C.HOUR
ORDER BY C.HOUR ASC;