-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF F
    INNER JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS ORDERS
        FROM JULY
        GROUP BY FLAVOR
    ) J ON J.FLAVOR = F.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.ORDERS) DESC
LIMIT 3;