-- 코드를 입력하세요
SELECT A.AUTHOR_ID AS AUTHOR_ID, A.AUTHOR_NAME AS AUTHOR_NAME, 
    B.CATEGORY AS CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
    INNER JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID
    INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = '2022' AND MONTH(S.SALES_DATE) = '1'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC; 