SELECT H.HISTORY_ID AS HISTORY_ID, 
    C.DAILY_FEE DIV 100 * (100 - IFNULL(DISCOUNT_RATE, 0)) * (DATEDIFF(END_DATE, START_DATE)+1) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    INNER JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.CAR_TYPE = C.CAR_TYPE 
        AND ((DATEDIFF(END_DATE, START_DATE)+1 >= 90 AND DURATION_TYPE = '90일 이상')
        OR (DATEDIFF(END_DATE, START_DATE)+1 >= 30 AND DATEDIFF(END_DATE, START_DATE)+1 < 90 AND DURATION_TYPE = '30일 이상')
        OR (DATEDIFF(END_DATE, START_DATE)+1 >= 7 AND DATEDIFF(END_DATE, START_DATE)+1 < 30 AND DURATION_TYPE = '7일 이상'))
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;