-- 코드를 입력하세요
SELECT A.APNT_NO AS APNT_NO, P.PT_NAME AS PT_NAME, P.PT_NO AS PT_NO, 
    D.MCDP_CD AS MCDP_CD, D.DR_NAME AS DR_NAME, A.APNT_YMD AS APNT_YMD
FROM APPOINTMENT A
    INNER JOIN PATIENT P ON P.PT_NO = A.PT_NO
    INNER JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE A.APNT_CNCL_YMD IS NULL AND YEAR(A.APNT_YMD) = '2022'
    AND MONTH(A.APNT_YMD) = '4' AND DAY(A.APNT_YMD) = '13' AND D.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC;