-- 코드를 입력하세요
SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
INNER JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
WHERE CAR_TYPE = '세단' AND (MONTH(START_DATE) >= 10 AND YEAR(START_DATE) >= 2022 OR YEAR(START_DATE) >= 2023)
ORDER BY CAR_ID DESC;