-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, 
    ROUND(SUM(R.REVIEW_SCORE) / COUNT(*), 2) AS SCORE
FROM REST_REVIEW R
INNER JOIN REST_INFO I ON I.REST_ID = R.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;